export const USER_SEARCHED = "USER_SEARCHED";
export const SEARCH_CLEARED = "SEARCHED_CLEARED";
export const ADDED_TO_FAVORITES = "ADDED_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"